#!/bin/bash -eu

readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(dirname "$(realpath "$0")")"

source "$SCRIPT_DIR"/lib/package.sh

usage() {
    die <<EOM
Usage:
   $SCRIPT_NAME [OPTION]... MACHINE PROFILE MEDIA
   $SCRIPT_NAME [OPTION]... MACHINE.PROFILE.img

Builds an Gentoo image for a host named MACHINE using settings from
profiles/PROFILE and storing the result the MEDIA file.

The second form uses the MEDIA filename as template for the needed parameters.

Options:

  -h    print this help message
  -w    wipe MEDIA
  -q    log messages in scripting mode

Environment variables:

  WIPE     same as -w
  QUIET    same as -q

For further environment variables that can customize the packaging process,
see '$(realpath --relative-to="$(pwd)" $SCRIPT_DIR)/install -h'.

Sample invocation:

  sudo -E $0 gentoo.rpi4.img

EOM
}

while getopts :hwq OPTION; do
    case $OPTION in
        h) usage ;;
        w) WIPE=true ;;
        q) QUIET=true ;;
        \?) usage ;;
    esac
done
shift $((OPTIND-1))

if (( $# == 1 )); then
    MEDIA="$1"
    parse-media-name
elif (( $# == 3 )); then
    MACHINE="$1"
    PROFILE="$2"
    MEDIA="$3"
else
    usage
fi

[ -n "$MACHINE" ] || die "MACHINE parameter cannot be empty"
[ -n "$PROFILE" ] || die "PROFILE parameter cannot be empty"
[ -n "$MEDIA" ] || die "MEDIA parameter cannot be empty"

cd "$(dirname "$0")"

package

${QUIET:-false} || cat <<EOM

Created $MEDIA.

EOM
