#!/bin/bash -eu

readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(dirname "$(realpath "$0")")"

source "$SCRIPT_DIR"/lib/provision.sh

usage() {
    die <<EOM
Usage: $SCRIPT_NAME [OPTION]... FACET...

Provisions the host with the tools needed build and install Gentoo on a
Raspberry Pi 4.

Options:

  -h   print this help message

EOM
}

while getopts :h OPTION; do
    case $OPTION in
        h) usage ;;
        \?) usage ;;
    esac
done
shift $((OPTIND-1))

is-gentoo / || die "Host is not Gentoo"

cd "$SCRIPT_DIR"

echo
echo '---===[ Provisioning ]===---'
echo System: $(uname -a)
echo

while (( $# > 0 )); do
    echo Provisioning "'$1'" facet...
    source provision.d/facets/"$1".sh
    shift
done

${QUIET:-false} || cat <<EOM

The system has been provisioned.

EOM
