#!/bin/bash -eu

readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(dirname "$(realpath "$0")")"

source "$SCRIPT_DIR"/lib/update.sh

usage() {
    die <<EOM
Usage: $SCRIPT_NAME [OPTION]... PROFILE DEVICE

Updates the current Gentoo system according to PROFILE.

Options:

  -q    log messages in scripting mode
  -m    configure kernel before building
  -h    print this help message

Environment variables:

  QUIET         same as -q
  MENUCONFIG    same as -m

Sample invocation:

  sudo $0

EOM
}

while getopts :hwqm OPTION; do
    case $OPTION in
        q) QUIET=true ;;
        m) MENUCONFIG=true ;;
        h) usage ;;
        \?) usage ;;
    esac
done
shift $((OPTIND-1))

(( $# == 2 )) || usage

readonly MACHINE="$(hostname)"
readonly PROFILE="$1"
readonly DEVICE="$2"

[ -n "$PROFILE" ] || die 'please specify a non-empty profile'
[ -b "$DEVICE" ] || die "'$DEVICE' is not a block device"
[ -f profiles/"$PROFILE".sh ] || die "unsupported profile '$PROFILE'"

source profiles/"$PROFILE".sh

cd "$SCRIPT_DIR"

update

${QUIET:-false} || cat <<EOM

Gentoo has been updated.

EOM
