#!/bin/bash -eu

readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(dirname "$(realpath "$0")")"

source "$SCRIPT_DIR"/lib/upgrade.sh

usage() {
    die <<EOM
Usage: $SCRIPT_NAME [OPTION]... PROFILE

Upgrades the current Gentoo system according to PROFILE.

Options:

  -q    log messages in scripting mode
  -m    configure kernel before building
  -h    print this help message

Environment variables:

  QUIET         same as -q
  MENUCONFIG    same as -m

Sample invocation:

  sudo $0

EOM
}

while getopts :hwqm OPTION; do
    case $OPTION in
        q) QUIET=true ;;
        m) MENUCONFIG=true ;;
        h) usage ;;
        \?) usage ;;
    esac
done
shift $((OPTIND-1))

(( $# == 0 )) || usage

cd "$SCRIPT_DIR"

upgrade

${QUIET:-false} || cat <<EOM

Gentoo has been upgraded.

EOM
