name: test

on: [push]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Update packages
      run: sudo apt-get update

    - name: Setup aarch64 emulation
      run: sudo apt-get install -y qemu-user-binfmt

    - name: Provision builder
      run: sudo ./builder ./provision

    - name: Build image
      run: sudo ./builder env PASSWORD=test-S3cr3t ./package gentoo.virt.img

    - name: Test image
      run: ./test gentoo.virt.img

    - name: Test console
      run: sudo ./builder env PASSWORD=test-S3cr3t ./test-console gentoo.virt.img
