name: test

on:
  push:
    branches:
      - main

jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      PASSWORD: test-S3cr3t
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Enable multicast DNS
      run: |
        sudo apt-get install -y libnss-resolve
        sudo mkdir -p /etc/systemd/resolved.conf.d
        sudo cp .github/runners/multicast-dns.conf /etc/systemd/resolved.conf.d/
        sudo systemctl restart systemd-resolved
        sudo sed -i 's/^hosts:.*/hosts:          files resolve [!UNAVAIL=return] dns/' /etc/nsswitch.conf

    - name: Setup aarch64 emulation
      run: |
        sudo apt-get install -y qemu-user-binfmt
        sudo cp .github/runners/qemu-aarch64.conf /etc/binfmt.d/
        sudo systemctl restart systemd-binfmt

    - name: Cache builder
      uses: actions/cache@v3
      with:
        path: builder.img
        key: builder-${{ hashFiles('builder', 'lib/builder.sh', 'provision', 'lib/provision.sh', 'provision.d') }}

    - name: Provision builder
      run: sudo ./builder ./provision

    - name: Build image
      run: sudo --preserve-env=PASSWORD ./builder ./package gentoo.test.img

    - name: Test image
      run: sudo --preserve-env=PASSWORD ./builder ./test gentoo.test.img

    - name: Clean up
      run: |
        sudo umount -vR /tmp/builder-* || true
        sudo rmdir -v /tmp/builder-* || true
        sudo ip link delete tap0 || true
        sudo sync
