name: test

on:
  push:
    branches:
      - master

jobs:

  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Enable multicast DNS
      run: |
        sudo apt-get install -y libnss-resolve
        sudo mkdir -p /etc/systemd/resolved.conf.d
        sudo cp .github/runners/multicast-dns.conf /etc/systemd/resolved.conf.d/
        sudo systemctl restart systemd-resolved
        sudo sed -i 's/^hosts:.*/hosts:          files resolve [!UNAVAIL=return] dns/' /etc/nsswitch.conf

    - name: Setup aarch64 emulation
      run: |
        sudo apt-get install -y qemu-user-binfmt
        sudo cp .github/runners/qemu-aarch64.conf /etc/binfmt.d/
        sudo systemctl restart systemd-binfmt

    - name: Cache builder
      uses: actions/cache@v3
      with:
        path: builder.img
        key: builder-${{ hashFiles('builder', 'lib/builder.sh', 'provision', 'lib/provision.sh', 'provision.d') }}

    - name: Provision builder
      run: sudo ./builder ./provision

    - name: Build image
      run: sudo ./builder env PASSWORD=test-S3cr3t ./package gentoo.virt.img

    - name: Test image
      run: sudo ./builder ./test gentoo.virt.img

    - name: Test console
      run: sudo ./builder env PASSWORD=test-S3cr3t ./test-console gentoo.virt.img
